### ISSUE TITLE
Update submodules

### ISSUE THREAD

**Issue by mapreal19** [inukshuk/csl-styles#1]
I would like to get the latests styles. I've tried to update the submodules and make a PR for you. But I get the following error:

`error: no such remote ref e2c5358a6bde3ddd6c83e741b51dd3e603f1e1ce`

Maybe I can point out the latests commits manually?

**Comment by inukshuk** [comment]
Good call: it's been a while. I'll push out a new version.

For what it's worth, you can also use the styles repo (or any folder with styles) directly -- this gem is basically [just two lines](https://github.com/inukshuk/csl-styles/blob/master/lib/csl/styles.rb#L4).

**Comment by inukshuk** [comment]
Pushed 1.0.1.8  to rubygems

**Comment by mapreal19** [comment]
@inukshuk awesome! thank you!
