### ISSUE TITLE
failed to extract CSL data in 1.0.1.9 version of gem

### ISSUE THREAD

**Issue by jfmull** [inukshuk/csl-styles#3]
I upgraded my code to use 1.0.1.9 of this gem, and I saw the following error when trying to use the 'modern-language-association-8th-edition' style:
```
Traceback (most recent call last):
	9: from csl_styles_bug.rb:29:in `<main>'
	8: from /usr/local/lib/ruby/gems/2.5.0/gems/citeproc-1.0.9/lib/citeproc/processor.rb:113:in `render'
	7: from /usr/local/lib/ruby/gems/2.5.0/gems/citeproc-1.0.9/lib/citeproc/processor.rb:34:in `engine'
	6: from /usr/local/lib/ruby/gems/2.5.0/gems/citeproc-1.0.9/lib/citeproc/processor.rb:34:in `new'
	5: from /usr/local/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/engine.rb:22:in `initialize'
	4: from /usr/local/lib/ruby/gems/2.5.0/gems/citeproc-ruby-1.1.10/lib/citeproc/ruby/engine.rb:120:in `update!'
	3: from /usr/local/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/style.rb:21:in `load'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/loader.rb:31:in `load'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/loader.rb:64:in `extract_data_from'
/usr/local/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/loader.rb:90:in `rescue in extract_data_from': failed to extract CSL data from "modern-language-association-8th-edition": No such file or directory @ rb_sysopen - modern-language-association-8th-edition (CSL::ParseError)
```

This worked when using 1.0.1.8 of the gem.

## Steps to Reproduce
 I attached a script that reproduces this. It works when using 1.0.1.8, but fails when using 1.0.1.9. Run the script against 1.0.1.8 to see the success. And run the script against 1.0.1.9 to see the failure
[csl_styles_bug.zip](https://github.com/inukshuk/csl-styles/files/3241917/csl_styles_bug.zip)

## Expected Behavior
When running with 1.0.1.8, I see the following output:
```
He, Maosheng, et al. “A High-Resolution Model of Field-Aligned Currents through Empirical Orthogonal Functions Analysis ({MFACE}).” Geophysical Research Letters, vol. 39, no. 18, American Geophysical Union ({AGU}), Sept. 2012, doi:10.1029/2012gl053168.
```

## Actual Behavior
I see the error from above:
```
/usr/local/lib/ruby/gems/2.5.0/gems/csl-1.5.0/lib/csl/loader.rb:90:in `rescue in extract_data_from': failed to extract CSL data from "modern-language-association-8th-edition": No such file or directory @ rb_sysopen - modern-language-association-8th-edition (CSL::ParseError)
```

## System Configuration
ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
dependent gems (I kept these versions fixed):
bibtex-ruby:  4.4.7
citeproc: 1.0.9
citeproc-ruby: 1.1.10

**Comment by inukshuk** [comment]
I think the style was just renamed to `modern-language-association`. If you [look here](https://github.com/citation-style-language/styles/blob/master/modern-language-association.csl) it says that it is in fact version 8.
