### ISSUE TITLE
1.0.1.10 changes rendering in Chicago style of a date with a literal and `circa` set

### ISSUE THREAD

**Issue by jrochkind** [inukshuk/csl-styles#5]
csl-styles 1.0.1.10 changed the rendering of citations in my app in a way I wasn't expecting, and don't like. 

But I'm not sure if it actually constitutes a bug fix; not sure if it is simply mirroring changes in the upstream platform-independent csl styles; generally not sure what's going on. 

Reproduction:

```ruby
    chicago_style = ::CSL::Style.load("chicago-note-bibliography")
    en_us_locale  = ::CSL::Locale.load("en-US")

    citation_item = CiteProc::CitationItem.new(id: "scihist33yxwci") do |c|
        c.data = CiteProc::Item.new({
          "title" => "Test title", 
          "issued" => {"date-parts"=>[[2000, 1, 1], [2019, 10, 10]], 
                                 "circa"=>true, 
                                 "literal"=>"circa 2000–2019"}
        })
      end

    renderer = CiteProc::Ruby::Renderer.new(:format => CiteProc::Ruby::Formats::Html.new, :locale => en_us_locale)

    puts renderer.render(citation_item, chicago_style.bibliography).html_safe
```

You can see we have an `issued` date which is a range, set to circa, but also has the `literal` set. Because circa/ranges were not being output how we wanted, we supply a literal with exactly how we want them output. 

With csl-styles `1.0.1.0`, this outputs as:

    “Test Title,” circa 2000–2019.

Which is what we wanted. We gave it a literal, that's what we wanted. 

With csl-styles 1.0.1.10, it insists on adding brackets and a question mark:

    “Test Title,” [circa 2000–2019?].

(Verified versions of `citeproc-ruby` and `csl` gems don't matter here, just `csl-styles`). 

It's possible this is somehow more 'correct' for chicago style, although to me it seems confusing -- does the question mark just apply to the first date or to both? Should they both have question marks? Why the brackets in addition to the question marks? I feel that if I am supplying the literal, it ought to just use exactly what I supplied.  

Can you supply any insight in to why an upgrade to csl-styles resulted in this change, what's behind it and if it's considered actually an improvement?

**Comment by jrochkind** [comment]
(PS: Thanks for putting csl-styles in their own gem separate from `citeproc` and `csl`, so we can just lock to the version that does what we want here, without having to avoid `csl` and `citeproc` updates too! Appreciate the thought that went into this!)

**Comment by inukshuk** [comment]
This is caused by the update to Chicago Style 17th edition. If you [look here](https://github.com/citation-style-language/styles/blob/master/chicago-note-bibliography.csl#L786) and elsewhere in the `issued` macro the brackets and the question mark are being added explicitly. In this case it's probably best to take out the literal string.

Alternatively, you can keep using Chicago Style 16th edition which should still be available as style `chicago-note-bibliography-16th-edition`. Finally, you could also use your own, edited, copy of the CSL style.

**Comment by jrochkind** [comment]
Thanks for the quick and very helpful response @inukshuk!

If I take out the `literal` supplied, it ends up:

    “Test Title,” [circa 2000–2019?]

So it does know how to do a range now! The 16th edition style was not properly handling the range (as opposed to just one date), or the presence of "circa", was just ignoring both, is why I was passing a literal in the first place. 

The styling still seems suspicious to me -- can the circa in front *and* the question mark in back *and* the brackets... actually be correct chicago style?   It seems confusing to me. 

And it still seems like arguably a bug that when you do supply a literal, it wraps it in punctuation, it seems like it should just trust what you gave it. 

But I realize that can get a bit "how many angels on the head of a pin", and at any rate would be an issue for the upstream https://github.com/citation-style-language/styles/ repo. 

It's a great tip that I can explicitly use `chicago-note-bibliography-16th-edition`, to keep using exactly the styles I was before the update. I didn't realize how things worked with I guess `chicago-note-bibliography` just being an alias to "latest", and I can pin to a specific one instead? For now, I will do that, to maintain my app working as previous. That works well. 

And good reminder that making a custom style would also be possible. 

Thanks!
