### ISSUE TITLE
Styles submodule not being updated

### ISSUE THREAD

**Issue by Baroquem** [inukshuk/csl-styles#9]
Hi, 

The styles submodule is still pointing to `citation-style-language/styles-distribution,` but that repo has been deprecated and is no longer updated (see [here](https://github.com/citation-style-language/styles/tree/v1.0.2#versioning-and-style-distribution)). Can this be changed to use `citation-style-language/styles` instead?

**Comment by inukshuk** [comment]
Done and pushed 2.0.1. Thanks!

**Comment by Baroquem** [comment]
Wow, thanks for a very speedy response!
